version: '3.5'  

services:

    backend:
      build:
        context: .
        dockerfile: backend.Dockerfile
      image: backend
      ports:
       - 8000:8000
      volumes:
       - ./logs.txt:/app/backend-example-docker/logs.txt

    frontend:
      build:
        context: .
        dockerfile: frontend.Dockerfile
      image: frontend
      ports:
       - 5000:5000